apiVersion: v1
kind: Pod
metadata:
  name: pod-lables
  namespace: roboshop
  labels:
    name: roboshop
    project: personal
    environment: production
spec:
  containers:
    -  name: nginx
       image: nginx