apiVersion: v1
kind: Pod
metadata:
  name: pod-annotations
  namespace: roboshop
  labels:
    Project: roboshop
    enironment: production
  annotations:
    image.registry: "https://hub.docker.com/"
spec:
  containers:
    - name: nginx
      image: nginx
