apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  namespace: roboshop
  labels:
   name: "k8s"
   env: "dev"
spec:
  containers:
  - name: nginx-configmap
    image: nginx
    envFrom:
    - configMapRef:
      name: nginx-configmap