apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  namespace: roboshop
spec:
  containers:
    - name: nginx-configmap
      image: nginx
      labels:
        name: "k8s"
        env: "dev"
      envFrom:
      - configMapRef:
        name: nginx-configmap