apiVersion: v1
kind: Secret
metadata: 
  name: secrets-demo
  namespace: roboshop
  labels:
    name: "K8s practice"
    environment: "prod"
data:
  username: "ZW5jb2RlIGFkbWluCg=="
  password: "ZW5jb2RlIHBhc3N3b3JkMTIzCg=="