apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespace: roboshop
  labels:
    name: "kubernetes-secrets"
    project: "dev-project"
spec:
  containers:
    - name: ngnix-secrets
      image: nginx
      envFrom:
        - secretRef:
            name: secrets-demo